# Generated by Django 4.1 on 2024-01-24 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_task_completed_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='usage_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
