# Generated by Django 4.1 on 2024-02-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
